# Generated by Django 3.0.5 on 2023-07-18 20:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("standard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
