# Generated by Django 3.0.5 on 2023-07-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("standard", "0002_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
