# Generated by Django 4.2.3 on 2023-08-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("standard", "0003_auto_20230725_1235"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="digital",
            field=models.BooleanField(default=False),
        ),
    ]
